name: Bundle debug AAR

on: 
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

jobs:
  apk:
    name: Bundle Colorpicker AAR
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2.3.5
      - name: set up JDK 1.8
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 1.8
      - name: Bundle debug AAR
        run: bash ./gradlew bundleDebugAar --stacktrace
